// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassicTransactionReceivedType } from "./ClassicTransactionReceivedType";

export type ClassicTransactionReceived = { receiver: string, emitter: string, description: string, amount: string, date: string, inorout: ClassicTransactionReceivedType, };
