// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenType } from "./TokenType";

export type Config = { server_address: string, port: string, user_login: string, pub_key: string, priv_key: string, gitlab_token: string, gitlab_token_type: TokenType, is_testnet: boolean, password: string, server_login: string, };
