// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserStats = { balance: number, sent_count: bigint, received_count: bigint, total_sent: number, total_received: number, total_transactions: bigint, rank: bigint, };
